---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Atom.app
    - /Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/src
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  # Stops DS_Store's from popping up
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: 10to1 Marleen
    git_user_email: marleen@10to1.be
  - role: legit
  - role: hub

  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: cask_package
    package_name: java
  - role: brew_package
    package_name: android-sdk
  - role: brew_package
    package_name: android-ndk
  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb
  - role: brew_package
    package_name: redis

  ## VMs
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant

  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: intellij-idea
  - role: cask_package
    package_name: lighttable
  - role: brew_package
    package_name: vim
  - role: brew_package
    package_name: emacs

  # Dropbox etc.
  - role: cask_package
    package_name: atom